In [70]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\user_k\anaconda3\lib\site-packages (1.5.12)
Requirement already satisfied: requests in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (2.26.0)
Requirement already satisfied: certifi in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (2022.12.7)
Requirement already satisfied: urllib3 in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (1.26.7)
Requirement already satisfied: python-slugify in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: tqdm in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (4.62.3)
Requirement already satisfied: python-dateutil in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: six>=1.10 in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\user_k\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user_k\anaconda3\lib\site-packages (from requests->kaggle) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\user_k\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: colorama in c:\users\user_k\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.4)

In [71]:
pip install kaggle

Requirement already satisfied: kaggle in c:\users\user_k\anaconda3\lib\site-packages (1.5.12)
Requirement already satisfied: requests in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (2.26.0)
Requirement already satisfied: tqdm in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (4.62.3)
Requirement already satisfied: six>=1.10 in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (2022.12.7)
Requirement already satisfied: python-dateutil in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\user_k\anaconda3\lib\site-packages (from kaggle) (1.26.7)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\user_k\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\user_k\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user_k\anaconda3\lib\site-packages (from requests->kaggle) (3.2)
Requirement already satisfied: colorama in c:\users\user_k\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

In [72]:
import kaggle

In [73]:
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()

In [74]:
dataset_name = 'laotse/credit-risk-dataset'

In [75]:
import os

In [76]:
path = os.path.join(os.path.expanduser('~'), 'Downloads', 'kaggle_dataset')
kaggle.api.dataset_download_files(dataset_name, unzip=True, path=path)

In [77]:
a=kaggle.api.dataset_download_files(dataset_name, unzip=True, path=path)

In [78]:
import pandas as pd

In [79]:
Data=pd.read_csv(r"C:\Users\User_K\Downloads\kaggle_dataset\credit_risk_dataset.csv")

In [69]:
Data

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30